### ISSUE TITLE
[QUESTION] Is it thread safe?

### ISSUE THREAD

**Issue by avokhmin** [janfri/multi_exiftool#9]
Hello!

>  It is designed for dealing with multiple files at once by creating commands to call exiftool with various arguments, call it and parsing the results.

Here is nothing about thread safe. The question is: can I process N files in parallel mode with this gem in the Sidekiq/Xxx with `concurrency > 1`?

Thanks, 
Aleksei.

**Comment by janfri** [comment]
Could you give a code example?

**Comment by avokhmin** [comment]
@janfri , something like [this](https://gist.github.com/avokhmin/31d707d490c232dac9f58cf7c6532e3b)

but with `multi_exiftool` gem. 

Currently I use `concurrency: 1`

**Comment by janfri** [comment]
Your code does not work with `currency` > `1`?

The advantage of multi_exiftool over mini_exiftool is that if you have multiple files in the filesystem you can let Exiftool do the hard work with only one command-line call. For example
```ruby
# mini_exiftool
Dir['*/*.mp4'].each do |fn|
  video = MiniExiftool.new(fn)
  video.creator = 'Foo Bar'
  video.title = '12345'
  video.description = {
    software: 'Example',
    year:     Date.today.year,
  }.to_json
  # call the Exiftool command-line app for each fn
  video.save
end

# multi_exiftool
values = {
  creator: 'Foo Bar',
  title: '12345'
  description: {
    software: 'Example',
    year:     Date.today.year,
  }.to_json
# only one call of the Exiftool command-line app for all the files
errors = MultiExiftool.write(Dir['*/*.mp4'], values)
```
So the difference is about the count of command-line calls. This is an immense performance advantage if you have many files to handle in the same way.

Maybe you can refactor your code so that you first download all your files, then update all at once with one command of multi_exiftool and then upload them one after another.

I hope this help you a bit to understand the intention behind multi_exiftool.

**Comment by avokhmin** [comment]
@janfri , thanks! I thought about it, but I prefer to do all via small and +- fast jobs.
